name: 'My Action'
description: 'Description of my action'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  my-input:
    description: 'My Input'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'
        overwrite-settings: false

#    - id: download-jar
#      run: curl -O -L https://_:${{ inputs.github-token }}@maven.pkg.github.com/madytw/codeowners-action/org/acme/codeowners-action/999-SNAPSHOT/codeowners-action-999-SNAPSHOT.jar
#      shell: bash
#
#    - id: run
#      run: java -jar codeowners-action-999-SNAPSHOT.jar
#      shell: bash

    - id: install-jbang
      run: curl -Ls https://sh.jbang.dev | bash -s - app setup
      shell: bash
    - id: action
      run: ~/.jbang/bin/jbang --verbose --repos 'github=https://maven.pkg.github.com/madytw/codeowners-action/' --repos 'mavencentral' org.acme:codeowners-action:999-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
